# place = Place.create(name: "Home", address: "123 Fake Street, Chicago, IL 60600")
# place = Place.create(name: "Grandmas", address: "225 Comanche Street, Waukesha, WI 53100")
# place = Place.create(name: "The Cabin", address: "123 Sugarview Lane, Green Lake, WI 53500")
# place = Place.create(name: "Amanda and Wonjun's", address: "123 Hilly Lane, Portland, OR 97000")
# place = Place.create(name: "Box Car Hole, Links Course", address: "123 Wild Turkey Lane, Green Lake, WI 53500")